Добавляет разметку Главной страницы и каталога
htmlacademy-htmlcss/1811651-device-35 pull request #2
Opened 2022-09-27 08:00 UTC by ChemicalWitness

2022-09-28 03:42 UTC, Dima-Dim requested changes
Наверняка у вас была об этом информация, но вдруг нет, что маловероятно :) На первых порах, очень полезно проверять html с помощью валидатора validator.w3.org/nu/ Делать это, желатено, перед отправкой на проверку.

2022-09-28 03:42 UTC, Dima-Dim commented on catalog.html
> +          <span class="visually-hidden">Показать от меньшего к большему</span> <!--Это ведь кнопки т.к. они должны взаимодействовать без перезгрузки страницы с помощью JS?-->
Может быть по разному, но вариант с кнопкой и JS вполне может быть.

2022-09-28 03:42 UTC, Dima-Dim commented on catalog.html
> +            <button class="button visually-hidden">Подробнее</button>   <!--Это копка будет скрыта пока пользователь не наведет на карточку товара-->
Тогда она не может быть в ссылке, потому интерактивные элементы нельзя вкладывать в интерактивные элементы.

2022-09-28 03:42 UTC, Dima-Dim commented on catalog.html
> +          <p class="footer-contacts-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
Можно обойтись и без тега `p`.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +        <button class="catalog-toggle" type="button" value="Каталог товаров" name="catalog">Каталог товаров</button> <!--Это ведь кнопка? Она будет работать я так понимаю с JS. Элементы которые наход
Да.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +    </header> <!--В навигации я решил разделить на два списка, это пользовательское меню и просто меню-->
Нет :) Навигация должна быть только одна и это должна быть основная навигация, по основным разделам. Крове этой основной навигации в теге nav больше быть ничего не должно.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +        <!--Возможна ли такая разметка слайдера? Я немного с ним запутался. Я так понял нужно обренуть в слайдере картинку, заголовок, текст, характеристику с кнопкой в контейнер и этот контейнер дол
Да, этот контейнер называется слайд и из этих слайдов состоит слайдер.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +              <img class="catalog-categories-image" src="">
Это не конетные изображения, в разметке их быть не должно.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +              <p class="catalog-categories-text">Виртуальная реальность</p>
Возможно тег `p` тут тоже будет лишним.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +      <section class="benefits">   <!--Я так понял это "табуляция"? Я немного сомневаюсь в правильности своей разметки, так ли должно быть? Переключатся списки будет по JS?-->
Да список слева это табы, то что справа это контент, который этими табами переключается. Очень похоже на слайдер, на самом деле :)

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +            <img class="benefits-image" src="" alt="">
Тоже не контеные изображения.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +            <button class="button button-benefits-title button-benefits-current" type="button">Доставка</button>
Список табов сам по себе. Список с контентом этих табов сам по себе. Ещё раз, очень похоже на слайдер.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +          <img src="" alt="">
Тут я думаю ты уже понял что не все изображения нужно добавлять в разметку, а от лишних тегов нужно избавиться.

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +        <p class="about-text">Огромный выбор гаджетов не оставит равнодушным гика, который есть в каждом из нас.</p>   <!--возможно использовать тег <br>-->
Тег `br` тут использовать не нужно :)

2022-09-28 03:42 UTC, Dima-Dim commented on index.html
> +    <footer class="page-footer"> <!--Есть вопрос по самим секциям. Некоторым название классов прям не подходит.Футер состоит из 3-х блоков которые можно будет расположить по оси флекс контейнера, я п
Да, здесь можно использовать div-ы. Именно так и нужно поступать, когда секции трудно дать название, а контейнер нужен только для стилизации. Сейчас можно обойтись и без div-ов и добавить их во время стилизации, если они понадобятся.

2022-09-29 01:02 UTC, ChemicalWitness commented on catalog.html
> +            <button class="button visually-hidden">Подробнее</button>   <!--Это копка будет скрыта пока пользователь не наведет на карточку товара-->
Т.е. её надо вкладывать в тег li и все классы у кнопки оставить. Эта кнопка будет показываться при наведении на ссылку с помощью абсолютного позиционирования?

2022-09-29 01:28 UTC, ChemicalWitness commented on index.html
> +    </header> <!--В навигации я решил разделить на два списка, это пользовательское меню и просто меню-->
Немного не могу понять как её сверстать. Я пока пришел к тому что в навигации будет 2 списка и кнопка(при нажатии которой будет появляться каталог товаров). А логотип и форму с поиском по сайту можно вынести из неё и вложить в див. Я верно понимаю ?)

2022-09-29 09:28 UTC, Dima-Dim commented on catalog.html
> +            <button class="button visually-hidden">Подробнее</button>   <!--Это копка будет скрыта пока пользователь не наведет на карточку товара-->
Сейчас не нужно особо думать о стилизации, тебе это мешает делать разметку. Это и про позиционирование и про классы. Всё что тебе сейчас нужно учитывать это один интерактивный элемент нельзя вкладывать в другой интерактивный элемент. Нужен ли тут тег `a` - вопрос. Если его не будет, то и с кнопкой проблем не будет.

2022-09-29 09:33 UTC, Dima-Dim commented on index.html
> +    </header> <!--В навигации я решил разделить на два списка, это пользовательское меню и просто меню-->
Не можешь понять как стилизовать или как разметить? Сейчас нужно только разменить логично и семантично.
Логотип и форму НУЖНО выенсти из тега nav.

2022-10-01 09:11 UTC, Dima-Dim requested changes
Нужно деделать разметку слайдера.

2022-10-01 09:11 UTC, Dima-Dim commented on index.html
> +          <!--Возможна ли такая разметка слайдера? Я немного с ним запутался. Я так понял нужно обренуть в слайдере картинку, заголовок, текст, характеристику с кнопкой в контейнер и этот контейнер д
Я вроде что-то писал по этому поводу, но сейчас не вижу тут этой информации. На всякий случай повторю.
"нужно обренуть в слайдере картинку, заголовок, текст, характеристику с кнопкой в контейнер" - да и это будет называться слайдом. Их будет несколько и все они будет частью слайдера.
Сейчас не вижу выделения этой информации в один слайд. Есть какая-то заготовка, но она не соответствует описанной тобой же логике.

2022-10-01 09:11 UTC, Dima-Dim commented on catalog.html
> +          <span class="visually-hidden">Показать от меньшего к большему</span> <!--Это ведь кнопки т.к. они должны взаимодействовать без перезгрузки страницы с помощью JS?-->
Эта часть может быть организована по разному, но то как ты предлагаешь тоже возможно.

2022-10-01 09:11 UTC, Dima-Dim commented on catalog.html
> +          <button class="button visually-hidden" type="button">Подробнее</button> <!--Это кнопка будет скрыта пока пользователь не наведет на карточку товара-->
Хорошо.

2022-10-01 09:11 UTC, Dima-Dim commented on catalog.html
> +      <section class="footer-copyright">
Нет же заголовка :) значит div. Секция тут перебор.

2022-10-03 11:02 UTC, merged